Repository flavia-dantas/burger-queen-api-client, pull requests merged in 2022-06, with the labels that each got.

#38 feat: logout
  src/components/Header/index.js
Labels: feat

#39 Feat/styles
  src/components/Button/style.css
  src/components/ButtonCountItems/style.css
  src/components/Header/style.css
  src/components/Input/style.css
  src/components/Layout/style.css
  src/components/MenuCard/style.css
  src/components/OrdersCard/style.css
  src/pages/Login/style.css
  src/pages/Menu/index.js
  src/pages/Menu/style.css
  src/pages/Register/style.css
  src/variables.css
Labels: feat

#40 feat: header kitchen page
  src/pages/Kitchen/index.js
Labels: feat

#41 Feat/add card item complement
  public/index.html
  src/components/MenuCard/index.js
  src/components/MenuCard/style.css
  src/pages/Menu/index.js
Labels: feat

#42 Feat/styles
  src/components/Header/index.js
  src/components/Header/style.css
  src/pages/Menu/style.css
Labels: feat, refactor

#43 feat: change color buttons on menu page
  src/pages/Menu/index.js
Labels: feat

#44 Refactor/menu page functions
  src/pages/Menu/index.js
Labels: refactor

#45 refactor: filter menu and storage on useStates
  src/pages/Menu/index.js
Labels: refactor

#46 Refactor/menu page
  src/components/Input/style.css
  src/pages/Menu/index.js
  src/pages/Menu/style.css
Labels: refactor

#47 Feat/error handle
  src/components/ErrorMessage/index.js
  src/components/ErrorMessage/style.css
  src/pages/Login/index.js
  src/pages/Login/style.css
  src/pages/Menu/index.js
  src/pages/Register/index.js
  src/services/error.js
Labels: feat, refactor

#48 feat: show order items details
  src/components/ItemCommand/index.js
  src/components/ItemCommand/style.css
  src/pages/Menu/index.js
Labels: feat

#49 feat: add button OrdersCard component
  src/components/OrdersCard/index.js
Labels: feat

#50 feat: setTimeOut error messages
  src/data/index.js
  src/pages/Login/index.js
  src/pages/Menu/index.js
  src/pages/Register/index.js
Labels: feat

#51 Refactor/filter function menu page
  src/data/index.js
  src/pages/Menu/index.js
Labels: refactor

#52 Refactor/button component
  src/components/Button/index.js
  src/components/OrdersCard/index.js
  src/pages/Kitchen/index.js
  src/pages/Login/index.js
  src/pages/Menu/index.js
  src/pages/Register/index.js
Labels: refactor

#53 Feat/modal component
  src/components/Modal/index.js
  src/components/Modal/styles.css
  src/pages/Menu/index.js
Labels: feat

#54 Feat/update status
  src/components/OrdersCard/index.js
  src/data/index.js
  src/pages/Kitchen/index.js
  src/pages/Menu/index.js
  src/services/products.js
Labels: feat

#56 Refactor/helper functions
  src/data/index.js
  src/helper/filterMenu.js
  src/helper/hideErrorMessage.js
  src/helper/index.js
  src/helper/sortData.js
  src/pages/Kitchen/index.js
  src/pages/Login/index.js
  src/pages/Menu/index.js
  src/pages/Register/index.js
Labels: refactor

#57 feat: format date
  package-lock.json
  package.json
  src/pages/Kitchen/index.js
Labels: feat

#58 Refactor/components
  src/components/ItemCommand/index.js
  src/components/MenuCard/index.js
  src/components/OrdersCard/index.js
Labels: refactor

#59 feat: preparation time
  src/helper/preparationTime.js
  src/helper/sortData.js
  src/pages/Kitchen/index.js
Labels: feat

#60 Refactor/kitchen page
  src/components/ItemCommand/index.js
  src/components/MenuCard/index.js
  src/components/OrdersCard/index.js
  src/components/OrdersCard/style.css
  src/components/ProductsOrder/index.js
  src/helper/filterData.js
  src/helper/filterMenu.js
  src/helper/index.js
  src/helper/statusVerification.js
  src/pages/Kitchen/index.js
  src/pages/Kitchen/style.css
  src/pages/Menu/index.js
Labels: bug, feat, refactor

#63 fix: filter functions
  src/helper/filterData.js
  src/helper/index.js
  src/pages/Kitchen/index.js
  src/pages/Menu/index.js
  src/pages/OrdersDelivery/index.js
Labels: bug

#64 feat: orders history page
  src/pages/OrdersHistory/index.js
  src/pages/OrdersHistory/style.css
Labels: feat

#65 Refactor/style pages
  src/pages/Kitchen/style.css
  src/pages/OrdersDelivery/index.js
  src/pages/OrdersDelivery/style.css
Labels: feat, refactor

#66 Feat/header buttons
  src/assets/delivery.svg
  src/assets/history.svg
  src/assets/home.svg
  src/components/Header/index.js
  src/components/Header/style.css
  src/pages/Login/index.js
  src/pages/Menu/index.js
  src/pages/Register/index.js
  src/services/localStorage.js
Labels: feat

#67 Refactor/styles
  src/components/Header/style.css
  src/components/Modal/styles.css
  src/pages/Kitchen/index.js
  src/pages/Kitchen/style.css
  src/pages/Menu/style.css
  src/pages/OrdersDelivery/index.js
  src/pages/OrdersDelivery/style.css
  src/pages/OrdersHistory/index.js
  src/pages/OrdersHistory/style.css
  src/variables.css
Labels: refactor

#68 feat: footer
  src/components/Footer/index.js
  src/components/Footer/style.css
  src/components/Layout/index.js
  src/components/Layout/style.css
Labels: feat

#69 Feat/private routes
  src/pages/Kitchen/index.js
  src/pages/Menu/index.js
  src/pages/OrdersDelivery/index.js
  src/routes.js
Labels: feat

#70 fix: redirects to netlify deploy
  public/_redirects
Labels: bug

#71 docs: readme
  README.md
  README.old.md
  src/assets/img/Burguer-Queen1.png
  src/assets/img/flavia-almeida.jpg
  src/assets/img/historia-usuario1.png
  src/assets/img/historia-usuario2.png
  src/assets/img/historia-usuario3.png
  src/assets/img/historia-usuario4.png
  src/assets/img/ludmila-magalhães.png
  src/assets/img/paleta-de-cores.png
  src/assets/img/prototipo-alta-fidelidade1.png
  src/assets/img/prototipo-alta-fidelidade2.png
Labels: documentation

#72 docs: update readme
  README.md
Labels: documentation
