Repository flavia-dantas/burger-queen-api-client, pull requests merged in 2022-05, with the labels that each got.

#1 style: firsts configs eslint and editorconfig
  .editorconfig
  .eslintrc
Labels: style

#2 feat: button component
  src/components/Button/button.js
Labels: feat

#3 feat: input component
  src/components/Input/input.js
  src/components/Input/style.css
Labels: feat

#4 feat: WIP page register
  src/App.js
  src/pages/Register/register.js
Labels: feat

#7 feat: create routes
  package-lock.json
  package.json
  src/App.js
  src/pages/Register/register.js
  src/routes.js
Labels: feat

#6 feat: WIP login page
  src/pages/Login/index.js
Labels: feat

#5 fix: rules eslint and import
  .eslintrc
  src/components/Button/button.js
Labels: bug, style

#8 docs: change files name
  src/App.test.js
  src/components/Button/index.js
  src/components/Input/index.js
  src/index.js
  src/pages/Login/index.js
  src/pages/Register/index.js
  src/routes.js
  src/setupTests.js
Labels: documentation

#9 feat: WIP api request to create user
  src/pages/Register/index.js
  src/services/auth.js
Labels: feat

#10 feat: WIP errors api request to create user
  src/pages/Register/index.js
  src/services/error.js
Labels: feat

#11 Refactor/components
  src/components/Button/index.js
  src/components/Input/index.js
  src/pages/Login/index.js
  src/pages/Register/index.js
Labels: refactor

#12 Refactor/register page
  src/pages/Register/index.js
  src/services/auth.js
Labels: refactor

#13 feat: API request to loginUser
  src/pages/Login/index.js
  src/services/auth.js
Labels: feat

#14 feat: add localStorage
  src/pages/Login/index.js
  src/pages/Register/index.js
  src/services/localStorage.js
Labels: feat

#15 feat: WIP error messeges to users
  src/components/MessageStatusCode/index.js
  src/pages/Login/index.js
  src/pages/Register/index.js
  src/services/error.js
Labels: feat

#16 docs: update gitignore after deploy on netlify
  .gitignore
Labels: documentation

#17 docs: create menu, kitchen and order status page files
  src/pages/Kitchen/index.js
  src/pages/Menu/index.js
  src/pages/OrderStatus/index.js
Labels: documentation

#18 Feat/routes
  src/pages/Login/index.js
  src/routes.js
Labels: feat

#19 Feat/error messages
  src/pages/Login/index.js
  src/pages/Register/index.js
  src/services/error.js
Labels: feat

#21 Feat/menu page
  src/pages/Menu/index.js
  src/services/products.js
Labels: feat

#22 Feat/menu card component
  src/components/Button/style.css
  src/components/MenuCard/index.js
  src/components/MenuCard/style.css
  src/pages/Menu/index.js
  src/pages/Menu/style.css
  src/style.css
Labels: feat

#23 feat: WIP button count items component
  src/components/ButtonCountItems/index.js
  src/components/ButtonCountItems/style.css
  src/pages/Menu/index.js
Labels: feat

#25 feat: button count items working
  src/pages/Menu/index.js
Labels: feat

#26 feat: add items menu in an array
  src/pages/Menu/index.js
Labels: feat

#27 Feat/create command
  src/pages/Menu/index.js
Labels: feat

#28 Feat/delete item command
  src/assets/trash_can.svg
  src/components/ItemCommand/index.js
  src/pages/Menu/index.js
Labels: feat

#29 Feat/header
  src/assets/exit.svg
  src/assets/logo.svg
  src/assets/shopping_cart.svg
  src/components/Header/index.js
  src/components/Header/style.css
  src/pages/Menu/index.js
Labels: feat

#31 feat: create order
  src/pages/Menu/index.js
Labels: feat

#32 fix: remove spread operator from storage order
  src/pages/Menu/index.js
Labels: bug

#33 Feat/get orders
  src/components/OrdersCard/index.js
  src/components/OrdersCard/style.css
  src/components/ProductsOrder/index.js
  src/pages/Kitchen/index.js
  src/pages/Kitchen/style.css
  src/services/products.js
Labels: feat

#34 Feat/style components
  src/components/Button/style.css
  src/components/Input/style.css
Labels: feat

#35 Feat/style login page
  src/pages/Login/index.js
  src/pages/Login/style.css
  src/style.css
Labels: feat

#36 refactor: update restaurant name
  src/services/auth.js
Labels: refactor

#37 Feat/styles
  public/burger.svg
  public/index.html
  src/assets/logo.svg
  src/assets/shopping_cart.svg
  src/components/Button/index.js
  src/components/Button/style.css
  src/components/ButtonCountItems/index.js
  src/components/ButtonCountItems/style.css
  src/components/Header/index.js
  src/components/Input/index.js
  src/components/Input/style.css
  src/components/ItemCommand/index.js
  src/components/ItemCommand/style.css
  src/components/Layout/index.js
  src/components/Layout/style.css
  src/components/MessageStatusCode/index.js
  src/components/MessageStatusCode/style.css
  src/pages/Login/index.js
  src/pages/Login/style.css
  src/pages/Menu/index.js
  src/pages/Menu/style.css
  src/pages/Register/index.js
  src/pages/Register/style.css
Labels: feat, refactor
